apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-files-pvc
  labels:
    app.kubernetes.io/name: {{ .Values.image.name }}
spec:
  accessModes:
{{- if and .Values.persistence .Values.persistence.accessModes }}
{{ toYaml .Values.persistence.accessModes | indent 4 }}
{{- else }}
    - ReadWriteOnce
{{- end }}
  resources:
    requests:
{{- if and .Values.persistence .Values.persistence.size }}
      storage: {{ .Values.persistence.size }}
{{- else }}
      storage: 1Gi
{{- end }}
{{- if and .Values.persistence .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
  volumeMode: Filesystem
